### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by hadim** [datamol-org/datamol-org.github.io#1]
@MichelML usually for a GH org website with GH-pages, the repo is called `organization.github.io` so if you rename it `datamol-org.github.io` the URL will be https://datamol-org.github.io/ instead of https://datamol-org.github.io/datamol-landing/

(not really critical, just letting you know)

Also currently we have the static HTML on `master` and the website is served by `master`, if you want to introduce a build step you can have your source code on `master` and the CI to push to `gh-pages`. The website will be served by `gh-pages`. If we stick with pure HTML, this is not necessary.

**Comment by MichelML** [comment]
do you have access to the settings @hadim ?

**Comment by MichelML** [comment]
I think any ci or multi-branch is overkill at this point like you said.

**Comment by MichelML** [comment]
renamed done

**Comment by hadim** [comment]
You and Manu are owners of the org like me so we should have the same permission.
